#!/usr/bin/env bash

set -o errexit

VERSION=$(git describe --tags --always)

go get github.com/mitchellh/gox
mkdir build && cd build
gox  -ldflags "-X github.com/zaypen/jbt/version.Version=$VERSION" -osarch="linux/amd64 darwin/amd64 windows/amd64" -output="{{.OS}}_{{.Arch}}/{{.Dir}}" ../...
